import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { ItemsProvider } from '@/contexts/items'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Shopping list',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ItemsProvider>{children}</ItemsProvider>
      </body>
    </html>
  )
}
